# Generated by Django 6.0.5 on 2026-05-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(max_length=5)),
            ],
        ),
    ]
